services:
  - type: web
    name: price-crawler-server
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: RENDER
        value: "true"
