services:
  - type: web
    name: price-crawler-server
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm run start
envVars:
  - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
    value: "false"
  - key: RENDER
    value: "true"
